### PR TITLE
make header logo into a link

### PR DESCRIPTION
**Pull request by abitsalihu**
The header logo is a link that will redirect back to the `index.html` page. :)

### CODE REVIEW

**Comment by ATechAjay** [comment]
See the another issues, I'm going to see the changes...

**Comment by ATechAjay** [comment]
it is not working, plz test before commit...

Fix the size of the logo with responsive!

**Comment by abitsalihu** [comment]
@ATechAjay Everything seems to be working fine on my end?
Please check the videos below for comparison between how it was and how it is now, there is no difference in appearance just the functionality.

You can check the code in the console as well.

`How it was :` 

https://user-images.githubusercontent.com/94648837/194288538-46a752dc-bb60-4c8d-a490-3d8a8c4fec36.mov

`How I fixed it :` 


https://user-images.githubusercontent.com/94648837/194288638-6973fa8a-f937-4ae3-b83e-1c9e1003edb8.mov

**Comment by ATechAjay** [comment]
Debugging the code, because there is conflicts between previous code with your code.

Just run **git pull** and you will receive all changes into your PC, then start debugging.

All the best:)

**Comment by abitsalihu** [comment]
@ATechAjay I believe it is fixed now, please review it.

**Pull request merged**
